# Site
title:              Baspar
subtitle:           Laine Bastien
description:        "Hey there! I'm Baspar, and welcome to my website and blog"
locale:             en_US
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Collection
collections:
  miniposts:
    output: true
    permalink: "/miniposts/:title/"
  posts:
    output: true
    permalink: "/posts/:title/"

# Jekyll
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         assets/css
  style:            compressed

# Comments
disqus_shortname:   baspar

# Social
analytics-id:       "default"
linkedin:           bastien-laine-196977109
github:             baspar

# personal
location:           Singapore
email:              me@bastien-laine.io
telegram:           baspar

# Gems
plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-paginate-v2

pagination:
  enabled: true
  permalink: :num/
  trail:
    before: 2
    after: 2

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile, old]
